### ISSUE TITLE
bboczeng@gmail.com can not push to master

### ISSUE THREAD

**Issue by bboczeng** [tonyhong272/MusicML#1]

**Comment by bboczeng** [comment]
I think it is still better we can work on the same repository. And it is also very clear if our work  is orthogonal, nothing will change on other's side

**Comment by tonyhong272** [comment]
I have added you to collabrator. you can push now to this repository.

**Comment by tonyhong272** [comment]
@bboczeng I have added you to collabrator. you can push now to this repository.

**Comment by tonyhong272** [comment]
You can always raise a pull request if not a collaborator. That's how people usually contribute. @bboczeng

**Comment by bboczeng** [comment]
Thanks~

**Comment by QGB** [comment]
bboczeng
